services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: onlyfriends-user
    ports:
      - "8002:8002"
    networks:
      - onlyfriends

  importer-service:
    build:
      context: ./recommendation-service 
      dockerfile: Dockerfile
    image: onlyfriends-recommendation
    depends_on:
      - weaviate      
      - user-service 
    environment:
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE}
      - WEAVIATE_HOST=weaviate 
      - WEAVIATE_HTTP_PORT=8080
      - WEAVIATE_GRPC_PORT=50051
    command: ["python", "importingData.py"] 
    networks:
      - onlyfriends

  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    image: onlyfriends-search
    ports:
      - "8004:8004"
    networks:
      - onlyfriends

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - DEFAULT_VECTORIZER_MODULE=none
      - TRANSFORMERS_INFERENCE_API=https://api-inference.huggingface.co/models/sentence-transformers/all-MiniLM-L6-v2
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - onlyfriends

networks:
  onlyfriends:
    driver: bridge

volumes:
  weaviate_data: